In [4]:
import pandas as pd 
import sqlite3

In [6]:
df_csv = pd.read_csv('data.csv')
df_csv.head()

   id     name  age      city
0   1    Alice   25  New York
1   2      Bob   30    London
2   3  Charlie   35     Paris

In [8]:
df_excel = pd.read_excel('data.xlsx')
df_excel.head()

   id     name  age      city
0   1    Alice   25  New York
1   2      Bob   30    London
2   3  Charlie   35     Paris

In [9]:
df_json = pd.read_json('data.json')
df_json.head()

   id     name  age      city
0   1    Alice   25  New York
1   2      Bob   30    London
2   3  Charlie   35     Paris

In [12]:
conn = sqlite3.connect('example.db')
df_sql = pd.read_sql_query('select * from my_table', conn)
df_sql.head()

   id     name  age      city
0   1    Alice   25  New York
1   2      Bob   30    London
2   3  Charlie   35     Paris