                  Imputing the data(Filling the nan vales with Mean or Median or Mode)

In [1]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer

In [3]:
df = pd.DataFrame({'S.no':[1,2,3,4,5,6],'age':[23,np.nan,34,42,np.nan,26],
'salary':[10000,20000,np.nan,50000,np.nan,45000],'city':["Bhopal","Indore",np.nan,"Ujjain",np.nan,np.nan]})
display(df)

   S.no   age   salary    city
0     1  23.0  10000.0  Bhopal
1     2   NaN  20000.0  Indore
2     3  34.0      NaN     NaN
3     4  42.0  50000.0  Ujjain
4     5   NaN      NaN     NaN
5     6  26.0  45000.0     NaN

                                      Mean imputer

In [4]:
mean_imputer = SimpleImputer(strategy='mean')
df_mean = df.copy()
df_mean[["age","salary"]] = mean_imputer.fit_transform(df[["age","salary"]])
print("\n\n Imputed Data is here")
display(df_mean)

 Imputed Data is here

   S.no    age   salary    city
0     1  23.00  10000.0  Bhopal
1     2  31.25  20000.0  Indore
2     3  34.00  31250.0     NaN
3     4  42.00  50000.0  Ujjain
4     5  31.25  31250.0     NaN
5     6  26.00  45000.0     NaN

                                    Median Imputer

In [6]:
median_imputer = SimpleImputer(strategy = "median")
df_median = df.copy()
df[["age","salary"]] = median_imputer.fit_transform(df[["age","salary"]])
print("\n\n Imputed Data is here")
display(df_median)

 Imputed Data is here

   S.no   age   salary    city
0     1  23.0  10000.0  Bhopal
1     2  30.0  20000.0  Indore
2     3  34.0  32500.0     NaN
3     4  42.0  50000.0  Ujjain
4     5  30.0  32500.0     NaN
5     6  26.0  45000.0     NaN

                                 Mode Imputer

In [11]:
mode_imputer = SimpleImputer(strategy='most_frequent')
df_mode = df.copy()
df[["city"]] = mode_imputer.fit_transform(df[["city"]])
print("\n\n Imputed Data is here")
display(df_mode)

 Imputed Data is here

   S.no   age   salary    city
0     1  23.0  10000.0  Bhopal
1     2  30.0  20000.0  Indore
2     3  34.0  32500.0  Bhopal
3     4  42.0  50000.0  Ujjain
4     5  30.0  32500.0  Bhopal
5     6  26.0  45000.0  Bhopal

                                        random imputer