## Encoding Technique
- Label Encoding
- Ordinal Encoding
- One Hot Encoding

In [2]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd

In [3]:
df = pd.DataFrame({
    'fruits':['Apple','Orange','Apple','Peach','orange'],
    'color':['Red','Blue','Red','Blue','yellow']
})
display(df)

   fruits   color
0   Apple     Red
1  Orange    Blue
2   Apple     Red
3   Peach    Blue
4  orange  yellow

## Lable Encoder

In [4]:
le_fruits = LabelEncoder()
le_color = LabelEncoder()

In [5]:
df['Encoded_fruits'] = le_fruits.fit_transform(df['fruits'])
df['Encoded_colors'] = le_color.fit_transform(df['color'])
print("\n\n Encoded Data with the help of LabelEncoder")
display(df)

 Encoded Data with the help of LabelEncoder

   fruits   color  Encoded_fruits  Encoded_colors
0   Apple     Red               0               1
1  Orange    Blue               1               0
2   Apple     Red               0               1
3   Peach    Blue               2               0
4  orange  yellow               3               2

## Ordinal Encoder

In [6]:
from sklearn.preprocessing import OrdinalEncoder

In [29]:
df1 = pd.DataFrame({
    'Marks':[50,87,20,34,90],
    'Review':["Good","Best","Poor","Poor","Best"],
    'Effort':["Medium effort","High effort","Poor effort","Poor effort","High effort"]
})
display(df1)

   Marks Review         Effort
0     50   Good  Medium effort
1     87   Best    High effort
2     20   Poor    Poor effort
3     34   Poor    Poor effort
4     90   Best    High effort

In [31]:
review_order = ["Poor","Good","Best"]
result_order = ["Poor effort","Medium effort","High effort"]

In [32]:
ordinal_encoder = OrdinalEncoder(categories=[review_order,result_order])
df1[['review_encoded','effort_encoded']] = ordinal_encoder.fit_transform(df1[['Review','Effort']])
print("\n\n Encoded Data with help of Ordinal Encoder")
print(df1)

 Encoded Data with help of Ordinal Encoder
   Marks Review         Effort  review_encoded  effort_encoded
0     50   Good  Medium effort             1.0             1.0
1     87   Best    High effort             2.0             2.0
2     20   Poor    Poor effort             0.0             0.0
3     34   Poor    Poor effort             0.0             0.0
4     90   Best    High effort             2.0             2.0

## One Hot Encoding

In [26]:
df_One_hot_encoding = pd.get_dummies(df , columns=['fruits','color'])
print("\n\n Encoded data with help of One Hot Encoder")
df_One_hot_encoding

 Encoded data with help of One Hot Encoder

   Encoded_fruits  Encoded_colors  ...  color_Red  color_yellow
0               0               1  ...       True         False
1               1               0  ...      False         False
2               0               1  ...       True         False
3               2               0  ...      False         False
4               3               2  ...      False          True

[5 rows x 9 columns]