In [ ]:
# 09-03-2026

In [ ]:
# importing library

In [1]:
import pandas as pd
import numpy as np
import random
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\hp\anaconda3\lib\site-packages (1.5.1)
Requirement already satisfied: numpy>=1.19.5 in c:\users\hp\anaconda3\lib\site-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in c:\users\hp\anaconda3\lib\site-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: joblib>=1.2.0 in c:\users\hp\anaconda3\lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\hp\anaconda3\lib\site-packages (from scikit-learn) (3.5.0)

In [3]:
from sklearn.impute import SimpleImputer

In [ ]:
# 10-03-2026           --------------- Impute

In [13]:
data = {'id':[1,2,3,4,5,6],
        'age':[25,np.nan,30,35,np.nan,100],
        'salary':[50000,60000,np.nan,80000,90000,np.nan],
        'city':["new york","London",np.nan,"paris","London",np.nan]}

df = pd.DataFrame(data)
print("original data:")
display(df)

original data:

   id    age   salary      city
0   1   25.0  50000.0  new york
1   2    NaN  60000.0    London
2   3   30.0      NaN       NaN
3   4   35.0  80000.0     paris
4   5    NaN  90000.0    London
5   6  100.0      NaN       NaN

In [ ]:
# mean imputer

In [14]:
mean_imputer = SimpleImputer(strategy = 'mean')
df_mean = df.copy()
df_mean[["age","salary"]] = mean_imputer.fit_transform(df_mean[["age","salary"]])
print("\n Imputed mean Data:")
display(df_mean)

 Imputed mean Data:

   id    age   salary      city
0   1   25.0  50000.0  new york
1   2   47.5  60000.0    London
2   3   30.0  70000.0       NaN
3   4   35.0  80000.0     paris
4   5   47.5  90000.0    London
5   6  100.0  70000.0       NaN

In [ ]:
# median imputer

In [17]:
median_imputer = SimpleImputer(strategy = "median")
df_median = df.copy()
df_median[["age","salary"]] = median_imputer.fit_transform(df[["age","salary"]])
print("\n Imputed median Data:")
display(df_median)

 Imputed median Data:

   id    age   salary      city
0   1   25.0  50000.0  new york
1   2   32.5  60000.0    London
2   3   30.0  70000.0       NaN
3   4   35.0  80000.0     paris
4   5   32.5  90000.0    London
5   6  100.0  70000.0       NaN

In [ ]:
# mode Imputer

In [21]:
mode_imputer = SimpleImputer(strategy = "most_frequent")
df_mode = df.copy()
df_mode[["city"]] = mode_imputer.fit_transform(df[["city"]])
print("\n Imputed mode Data:")
display(df_mode)

 Imputed mode Data:

   id    age   salary      city
0   1   25.0  50000.0  new york
1   2    NaN  60000.0    London
2   3   30.0      NaN    London
3   4   35.0  80000.0     paris
4   5    NaN  90000.0    London
5   6  100.0      NaN    London

In [ ]:
# random imputation

In [22]:
df_random = df.copy()
def random_impute(series):
    filled = series.dropna().tolist()
    return series.apply(lambda x: random.choice(filled) if pd.isnull(x) else x)

for col in ['age','salary','city']:
    df_random[col] = random_impute(df_random[col])
    
print("\n Random Imputed Data:")
display(df_random)

 Random Imputed Data:

   id    age   salary      city
0   1   25.0  50000.0  new york
1   2   30.0  60000.0    London
2   3   30.0  50000.0    London
3   4   35.0  80000.0     paris
4   5   25.0  90000.0    London
5   6  100.0  90000.0     paris