In [1]:
import pandas as pd 
from sklearn.model_selection import train_test_split

In [3]:
df = pd.DataFrame({
    'Age':[12,34,56,75,67,56,56,44,89,34],
    'Salary':[20000,40000,25000,30000,32400,100200,130000,100000,40200,42592],
    'Purchased':[0,0,1,0,1,0,0,1,0,1]
})
print("Original Data:")
display(df)

Original Data:

   Age  Salary  Purchased
0   12   20000          0
1   34   40000          0
2   56   25000          1
3   75   30000          0
4   67   32400          1
5   56  100200          0
6   56  130000          0
7   44  100000          1
8   89   40200          0
9   34   42592          1

In [5]:
X = df[["Age","Salary"]]
y = df["Purchased"]

In [10]:
display(X)

   Age  Salary
0   12   20000
1   34   40000
2   56   25000
3   75   30000
4   67   32400
5   56  100200
6   56  130000
7   44  100000
8   89   40200
9   34   42592

In [9]:
display(y)

0    0
1    0
2    1
3    0
4    1
5    0
6    0
7    1
8    0
9    1
Name: Purchased, dtype: int64

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [17]:
display(X_train)
print(X_train.shape)

   Age  Salary
5   56  100200
0   12   20000
7   44  100000
2   56   25000
9   34   42592
4   67   32400
3   75   30000
6   56  130000

(8, 2)

In [18]:
display(X_test)
print(X_test.shape)

   Age  Salary
8   89   40200
1   34   40000

(2, 2)

In [19]:
display(y_test)
print(y_test.shape)

8    0
1    0
Name: Purchased, dtype: int64

(2,)

In [20]:
display(y_train)
print(y_train.shape)

5    0
0    0
7    1
2    1
9    1
4    1
3    0
6    0
Name: Purchased, dtype: int64

(8,)